### ISSUE TITLE
SPN Decode Logic Fault

### ISSUE THREAD

**Issue by d1c0** [jackm/j1939decode#1]
Line 308 in j1939decode.c must account for the length_in_bits when rightshifting. At the moment :

`uint64_t value_raw = ((*data) >> start_bit) & mask;`

Here is a scenario:

start_bit = 32; mask = 0xFFFF; length_in_bits = 16; data = 0x 1111 2222 DDDD 3333; // DDDD is the SPN we care about

After righshift 32 times, the value becomes 0x 0000 0000 1111 2222, and we extract 2222 after masking, instead of DDDD

Proposed fix:

`uint64_t value_raw = ((*data) >> (64 - start_bit - length_in_bits)) & mask;`

**Comment by jackm** [comment]
You are misinterpreting what the start bit signifies - you have the bit order backwards. The start bit is the _least significant bit_ of the SPN value, counting from the _least significant bit_ (right most bit) of the four data bytes. All numbers are zero-indexed.

In your example, if the message data was ` 0x11112222DDDD3333` and `0xDDDD` are the 16 bits that we want to extract, then the start bit for this SPN would be 16, not 32.

**Comment by d1c0** [comment]
That would work for byte-aligned values only. I understand that casting an array of bytes to uint64_t swaps the byte order around (in most architectures), but it certainly doesn't swap the bit order around. The J1939 DBC file give you the SPN positions in absolute bits counted from left to right, i.e. SPN position 0, length 1 (hypothetical, I know short lengths are usually 2 bits) is bit 0x80 in the first byte. You still have to right-shift it 7 times before masking, right?

**Comment by d1c0** [comment]
You are right of course. The DBC file counts bytes from left-to-right, but counts bits from right-to-left. This is obvious when comparing it to other J1939 Digial outputs, such as the Excel files, which use a more user-friendly convention, such as BYTE.BIT.
